image: node:10.15.3

pipelines:
  default:
    - step:
        # caches:
        #   - node
        script: # Modify the commands below to build your repository.
          - rm -rf node_modules
          - npm install
          - cd ./node_modules/ocn-bridge && npm run prepare && cd -
          - cp src/config/config.example.ts src/config/config.ts
          - npm run build
          - npm test
